server {
 listen 8080;
 server_tokens off;
 client_max_body_size 6m;
 location /api/ { proxy_pass http://backend:8000/api/; proxy_http_version 1.1; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; }
 location /assets/ { proxy_pass http://backend:8000/assets/; }
 location / { root /usr/share/nginx/html; try_files $uri /index.html; }
}

