export type Language='el'|'en';

const el={
  hierarchy:'Δομή μαθημάτων',
  students:'Φοιτητές',student:'Φοιτητής',presentationSubject:'Θέμα παρουσίασης',presentationDate:'Ημερομηνία παρουσιάσεων',manageStudents:'Διαχείριση φοιτητών',theme:'Χρωματική παλέτα',themeHint:'Επιλέξτε ένα ήπιο χρώμα για τον λογαριασμό σας.',logo:'Λογότυπο',uploadLogo:'Μεταφόρτωση λογοτύπου',logoUploaded:'Το λογότυπο μεταφορτώθηκε.',timeRemaining:'Υπόλοιπος χρόνος',seconds:'δευτερόλεπτα',
  app:'Ψηφοφορία Παρουσιάσεων',login:'Σύνδεση',username:'Όνομα χρήστη',password:'Κωδικός',fullName:'Ονοματεπώνυμο',dashboard:'Πίνακας',account:'Λογαριασμός',admin:'Διαχείριση',logout:'Έξοδος',language:'English',loading:'Φόρτωση…',
  lecturerDashboard:'Πίνακας διδάσκοντα',courses:'Μαθήματα',course:'Μάθημα',courseName:'Όνομα μαθήματος',description:'Περιγραφή',periods:'Ακαδημαϊκές περίοδοι',period:'Περίοδος',periodName:'Όνομα περιόδου',groups:'Ομάδες',group:'Ομάδα',groupTitle:'Τίτλος ομάδας',sessions:'Συνεδρίες',session:'Συνεδρία',sessionTitle:'Τίτλος συνεδρίας',sessionDate:'Ημερομηνία',add:'Προσθήκη',create:'Δημιουργία',cancel:'Άκυρο',save:'Αποθήκευση',noItems:'Δεν υπάρχουν καταχωρίσεις.',select:'Επιλέξτε…',
  addCourse:'Νέο μάθημα',addPeriod:'Νέα περίοδος',addGroup:'Νέα ομάδα',addSession:'Νέα συνεδρία',created:'Η καταχώριση δημιουργήθηκε επιτυχώς.',courseFirst:'Δημιουργήστε πρώτα ένα μάθημα.',periodFirst:'Δημιουργήστε πρώτα μία ακαδημαϊκή περίοδο.',groupFirst:'Δημιουργήστε πρώτα μία ομάδα.',
  users:'Χρήστες',lecturer:'Διδάσκων',addLecturer:'Νέος διδάσκων',temporaryPassword:'Προσωρινός κωδικός',passwordHint:'Τουλάχιστον 10 χαρακτήρες. Ο χρήστης θα τον αλλάξει στην πρώτη σύνδεση.',usernameHint:'3–100 χαρακτήρες: λατινικά γράμματα, αριθμοί, τελεία, παύλα ή κάτω παύλα.',active:'Ενεργός',inactive:'Ανενεργός',userCreated:'Ο διδάσκων δημιουργήθηκε. Θα πρέπει να αλλάξει τον προσωρινό κωδικό στην πρώτη σύνδεση.',
  branding:'Ιδρυματική ταυτότητα',universityName:'Ίδρυμα',schoolName:'Σχολή',departmentName:'Τμήμα',background:'Φόντο',none:'Χωρίς',solid:'Χρώμα',gradient:'Διαβάθμιση',backgroundValue:'Τιμή φόντου',saved:'Οι αλλαγές αποθηκεύτηκαν.',
  participationLink:'Σύνδεσμος συμμετοχής',presentations:'Παρουσιάσεις',withoutTitle:'Χωρίς τίτλο',votes:'ψήφοι',edit:'Επεξεργασία',open:'Άνοιγμα',skip:'Παράλειψη',restore:'Επαναφορά',close:'Κλείσιμο',activate:'Ενεργοποίηση',complete:'Ολοκλήρωση',confirmComplete:'Να ολοκληρωθεί οριστικά η συνεδρία;',reveal:'Αποκάλυψη αποτελεσμάτων',projector:'Προβολέας',presenterDetails:'Στοιχεία παρουσιαστή',title:'Τίτλος',results:'Αποτελέσματα',noEvaluated:'Δεν υπάρχουν αξιολογημένες παρουσιάσεις.',rank:'Κατάταξη',presenter:'Παρουσιαστής',score:'Βαθμός',
  live:'ΖΩΝΤΑΝΑ',presentation:'Παρουσίαση',submitRating:'Υποβολή αξιολόγησης',voteSaved:'Η ψήφος αποθηκεύτηκε. Μπορείτε να την αλλάξετε όσο η ψηφοφορία είναι ανοικτή.',sessionCompleted:'Η συνεδρία ολοκληρώθηκε',waitingNext:'Αναμονή επόμενης παρουσίασης',autoUpdate:'Η οθόνη θα ενημερωθεί αυτόματα.',votingOpen:'ΨΗΦΟΦΟΡΙΑ ΑΝΟΙΚΤΗ',waitingPresentation:'Αναμονή παρουσίασης',
  mandatoryPassword:'Υποχρεωτική αλλαγή κωδικού',changePassword:'Αλλαγή κωδικού',temporaryReplace:'Ο προσωρινός κωδικός πρέπει να αντικατασταθεί πριν συνεχίσετε.',currentPassword:'Τρέχων κωδικός',newPassword:'Νέος κωδικός',confirmPassword:'Επιβεβαίωση νέου κωδικού',passwordMismatch:'Οι νέοι κωδικοί δεν ταιριάζουν.',passwordChanged:'Ο κωδικός άλλαξε επιτυχώς.',
  removeManagement:'Ασφαλής διαχείριση',deactivate:'Απενεργοποίηση',reactivate:'Επανενεργοποίηση',delete:'Διαγραφή',archiveAction:'Αρχειοθέτηση',confirmDeactivate:'Να απενεργοποιηθεί ο χρήστης',confirmReactivate:'Να επανενεργοποιηθεί ο χρήστης',confirmDelete:'Να διαγραφεί οριστικά',confirmArchive:'Να αρχειοθετηθεί',actionDone:'Η ενέργεια ολοκληρώθηκε.',criterionScience:'Επιστημονική τεκμηρίωση',criterionClarity:'Σαφήνεια και οργάνωση',criterionThinking:'Κριτική σκέψη',draft:'Πρόχειρη',activeStatus:'Ενεργή',completed:'Ολοκληρωμένη',archived:'Αρχειοθετημένη',pending:'Σε αναμονή',votingOpenStatus:'Ανοικτή ψηφοφορία',closed:'Κλειστή',skipped:'Παραλείφθηκε',validation:'Ελέγξτε τα επισημασμένα πεδία.',required:'Το πεδίο είναι υποχρεωτικό.',invalidUsername:'Χρησιμοποιήστε 3–100 λατινικούς χαρακτήρες, αριθμούς, τελεία, παύλα ή κάτω παύλα.',passwordShort:'Ο κωδικός πρέπει να έχει τουλάχιστον 10 χαρακτήρες.',requestFailed:'Η ενέργεια απέτυχε. Δοκιμάστε ξανά.'
} as const;

const en:Record<keyof typeof el,string>={
  hierarchy:'Course structure',
  students:'Students',student:'Student',presentationSubject:'Presentation subject',presentationDate:'Presentation date',manageStudents:'Manage students',theme:'Color palette',themeHint:'Choose a muted color for your account.',logo:'Logo',uploadLogo:'Upload logo',logoUploaded:'Logo uploaded.',timeRemaining:'Time remaining',seconds:'seconds',
  app:'Presentation Voting',login:'Sign in',username:'Username',password:'Password',fullName:'Full name',dashboard:'Dashboard',account:'Account',admin:'Administration',logout:'Sign out',language:'Ελληνικά',loading:'Loading…',
  lecturerDashboard:'Lecturer dashboard',courses:'Courses',course:'Course',courseName:'Course name',description:'Description',periods:'Academic periods',period:'Period',periodName:'Period name',groups:'Groups',group:'Group',groupTitle:'Group title',sessions:'Sessions',session:'Session',sessionTitle:'Session title',sessionDate:'Date',add:'Add',create:'Create',cancel:'Cancel',save:'Save',noItems:'No entries yet.',select:'Select…',
  addCourse:'New course',addPeriod:'New period',addGroup:'New group',addSession:'New session',created:'The entry was created successfully.',courseFirst:'Create a course first.',periodFirst:'Create an academic period first.',groupFirst:'Create a group first.',
  users:'Users',lecturer:'Lecturer',addLecturer:'New lecturer',temporaryPassword:'Temporary password',passwordHint:'At least 10 characters. The user must change it at first sign-in.',usernameHint:'3–100 characters: Latin letters, numbers, dot, hyphen, or underscore.',active:'Active',inactive:'Inactive',userCreated:'The lecturer was created and must change the temporary password at first sign-in.',
  branding:'Institutional identity',universityName:'University',schoolName:'School',departmentName:'Department',background:'Background',none:'None',solid:'Solid color',gradient:'Gradient',backgroundValue:'Background value',saved:'Changes saved.',
  participationLink:'Participation link',presentations:'Presentations',withoutTitle:'Untitled',votes:'votes',edit:'Edit',open:'Open',skip:'Skip',restore:'Restore',close:'Close',activate:'Activate',complete:'Complete',confirmComplete:'Permanently complete this session?',reveal:'Reveal results',projector:'Projector',presenterDetails:'Presenter details',title:'Title',results:'Results',noEvaluated:'There are no evaluated presentations.',rank:'Rank',presenter:'Presenter',score:'Score',
  live:'LIVE',presentation:'Presentation',submitRating:'Submit rating',voteSaved:'Your vote was saved. You may change it while voting remains open.',sessionCompleted:'The session is complete',waitingNext:'Waiting for the next presentation',autoUpdate:'This screen will update automatically.',votingOpen:'VOTING OPEN',waitingPresentation:'Waiting for a presentation',
  mandatoryPassword:'Password change required',changePassword:'Change password',temporaryReplace:'You must replace the temporary password before continuing.',currentPassword:'Current password',newPassword:'New password',confirmPassword:'Confirm new password',passwordMismatch:'The new passwords do not match.',passwordChanged:'Password changed successfully.',
  removeManagement:'Safe management',deactivate:'Deactivate',reactivate:'Reactivate',delete:'Delete',archiveAction:'Archive',confirmDeactivate:'Deactivate user',confirmReactivate:'Reactivate user',confirmDelete:'Permanently delete',confirmArchive:'Archive',actionDone:'Action completed.',criterionScience:'Scientific documentation',criterionClarity:'Clarity and organization',criterionThinking:'Critical thinking',draft:'Draft',activeStatus:'Active',completed:'Completed',archived:'Archived',pending:'Pending',votingOpenStatus:'Voting open',closed:'Closed',skipped:'Skipped',validation:'Check the highlighted fields.',required:'This field is required.',invalidUsername:'Use 3–100 Latin letters, numbers, dots, hyphens, or underscores.',passwordShort:'The password must contain at least 10 characters.',requestFailed:'The action failed. Please try again.'
};

export type TranslationKey=keyof typeof el;
export const translations={el,en};
export const apiMessages:Record<Language,Record<string,string>>={
  el:{'Invalid credentials':'Λανθασμένα στοιχεία σύνδεσης','Not found':'Δεν βρέθηκε'},
  en:{'Λανθασμένα στοιχεία σύνδεσης':'Invalid username or password','Μη έγκυρος κωδικός':'Invalid current password','Ο νέος κωδικός πρέπει να είναι διαφορετικός':'The new password must be different','Το όνομα χρήστη υπάρχει ήδη':'That username already exists','Δεν βρέθηκε':'Not found','Μη έγκυρη επιλογή':'Invalid selection','Το μάθημα χρησιμοποιείται από ομάδα ή συνεδρία':'The course is used by a group or session','Η περίοδος χρησιμοποιείται από ομάδα ή συνεδρία':'The period is used by a group or session','Η ομάδα χρησιμοποιείται από συνεδρία':'The group is used by a session','Μόνο πρόχειρες ή DEMO συνεδρίες διαγράφονται οριστικά':'Only draft or demo sessions can be permanently deleted','Πάρα πολλές προσπάθειες· δοκιμάστε αργότερα':'Too many attempts; try again later','Πάρα πολλές υποβολές· περιμένετε λίγο':'Too many submissions; wait a moment'}
};

export function translateError(error:unknown,language:Language){
  const fallback=translations[language].requestFailed;
  const message=error instanceof Error?error.message:String(error||fallback);
  const known=apiMessages[language][message];
  if(known)return known;
  if(message.includes('username:')&&message.includes('pattern'))return translations[language].invalidUsername;
  if(message.includes('password:')&&message.includes('10'))return translations[language].passwordShort;
  if(message.includes('full_name:'))return `${translations[language].fullName}: ${translations[language].required}`;
  return message||fallback;
}
