export type Language='el'|'en';

const el={
  hierarchy:'Δομή μαθημάτων',
  students:'Φοιτητές',student:'Φοιτητής',presentationSubject:'Θέμα παρουσίασης',presentationDate:'Ημερομηνία παρουσιάσεων',manageStudents:'Διαχείριση φοιτητών',theme:'Χρωματική παλέτα',themeHint:'Επιλέξτε ένα ήπιο χρώμα για τον λογαριασμό σας.',logo:'Λογότυπο',uploadLogo:'Μεταφόρτωση λογοτύπου',logoUploaded:'Το λογότυπο μεταφορτώθηκε.',timeRemaining:'Υπόλοιπος χρόνος',seconds:'δευτερόλεπτα',
  app:'Ψηφοφορία Παρουσιάσεων',login:'Σύνδεση',username:'Όνομα χρήστη',password:'Κωδικός',fullName:'Ονοματεπώνυμο',dashboard:'Πίνακας',account:'Λογαριασμός',admin:'Διαχείριση',logout:'Έξοδος',language:'English',loading:'Φόρτωση…',
  lecturerDashboard:'Πίνακας διδάσκοντα',courses:'Μαθήματα',course:'Μάθημα',courseName:'Όνομα μαθήματος',description:'Περιγραφή',periods:'Ακαδημαϊκές περίοδοι',period:'Περίοδος',periodName:'Όνομα περιόδου',groups:'Ομάδες',group:'Ομάδα',groupTitle:'Τίτλος ομάδας',sessions:'Συνεδρίες',session:'Συνεδρία',sessionTitle:'Τίτλος συνεδρίας',sessionDate:'Ημερομηνία',add:'Προσθήκη',create:'Δημιουργία',cancel:'Άκυρο',save:'Αποθήκευση',noItems:'Δεν υπάρχουν καταχωρίσεις.',select:'Επιλέξτε…',
  addCourse:'Νέο μάθημα',addPeriod:'Νέα περίοδος',addGroup:'Νέα ομάδα',addSession:'Νέα συνεδρία',created:'Η καταχώριση δημιουργήθηκε επιτυχώς.',courseFirst:'Δημιουργήστε πρώτα ένα μάθημα.',periodFirst:'Δημιουργήστε πρώτα μία ακαδημαϊκή περίοδο.',groupFirst:'Δημιουργήστε πρώτα μία ομάδα.',
  users:'Χρήστες',lecturer:'Διδάσκων',addLecturer:'Νέος διδάσκων',temporaryPassword:'Προσωρινός κωδικός',passwordHint:'Τουλάχιστον 10 χαρακτήρες. Ο χρήστης θα τον αλλάξει στην πρώτη σύνδεση.',usernameHint:'3–100 χαρακτήρες: λατινικά γράμματα, αριθμοί, τελεία, παύλα ή κάτω παύλα.',active:'Ενεργός',inactive:'Ανενεργός',userCreated:'Ο διδάσκων δημιουργήθηκε. Θα πρέπει να αλλάξει τον προσωρινό κωδικό στην πρώτη σύνδεση.',
  branding:'Ιδρυματική ταυτότητα',universityName:'Ίδρυμα',schoolName:'Σχολή',departmentName:'Τμήμα',background:'Φόντο',none:'Χωρίς',solid:'Χρώμα',gradient:'Διαβάθμιση',backgroundValue:'Τιμή φόντου',saved:'Οι αλλαγές αποθηκεύτηκαν.',
  participationLink:'Σύνδεσμος συμμετοχής',presentations:'Παρουσιάσεις',withoutTitle:'Χωρίς τίτλο',votes:'ψήφοι',edit:'Επεξεργασία',open:'Άνοιγμα',skip:'Παράλειψη',restore:'Επαναφορά',close:'Κλείσιμο',activate:'Ενεργοποίηση',complete:'Ολοκλήρωση',confirmComplete:'Να ολοκληρωθεί οριστικά η συνεδρία;',reveal:'Αποκάλυψη αποτελεσμάτων',projector:'Προβολέας',presenterDetails:'Στοιχεία παρουσιαστή',title:'Τίτλος',results:'Αποτελέσματα',noEvaluated:'Δεν υπάρχουν αξιολογημένες παρουσιάσεις.',rank:'Κατάταξη',presenter:'Παρουσιαστής',score:'Βαθμός',
  live:'ΖΩΝΤΑΝΑ',presentation:'Παρουσίαση',submitRating:'Υποβολή αξιολόγησης',voteSaved:'Η ψήφος αποθηκεύτηκε. Μπορείτε να την αλλάξετε όσο η ψηφοφορία είναι ανοικτή.',sessionCompleted:'Η συνεδρία ολοκληρώθηκε',waitingNext:'Αναμονή επόμενης παρουσίασης',waitingForNextPresentation:'Αναμονή για την έναρξη της επόμενης ψηφοφορίας...',presentationQueue:'Σειρά παρουσιάσεων',autoUpdate:'Η οθόνη θα ενημερωθεί αυτόματα.',votingOpen:'ΨΗΦΟΦΟΡΙΑ ΑΝΟΙΚΤΗ',waitingPresentation:'Αναμονή παρουσίασης',
  mandatoryPassword:'Υποχρεωτική αλλαγή κωδικού',changePassword:'Αλλαγή κωδικού',temporaryReplace:'Ο προσωρινός κωδικός πρέπει να αντικατασταθεί πριν συνεχίσετε.',currentPassword:'Τρέχων κωδικός',newPassword:'Νέος κωδικός',confirmPassword:'Επιβεβαίωση νέου κωδικού',passwordMismatch:'Οι νέοι κωδικοί δεν ταιριάζουν.',passwordChanged:'Ο κωδικός άλλαξε επιτυχώς.',
  removeManagement:'Ασφαλής διαχείριση',deactivate:'Απενεργοποίηση',reactivate:'Επανενεργοποίηση',delete:'Διαγραφή',archiveAction:'Αρχειοθέτηση',confirmDeactivate:'Να απενεργοποιηθεί ο χρήστης',confirmReactivate:'Να επανενεργοποιηθεί ο χρήστης',confirmDelete:'Να διαγραφεί οριστικά',confirmArchive:'Να αρχειοθετηθεί',actionDone:'Η ενέργεια ολοκληρώθηκε.',  criterionScience:'Επιστημονική τεκμηρίωση',criterionClarity:'Σαφήνεια και οργάνωση',criterionThinking:'Κριτική σκέψη',draft:'Πρόχειρη',activeStatus:'Ενεργή',completed:'Ολοκληρωμένη',archived:'Αρχειοθετημένη',pending:'Σε αναμονή',votingOpenStatus:'Ανοικτή ψηφοφορία',closed:'Κλειστή',skipped:'Παραλείφθηκε',validation:'Ελέγξτε τα επισημασμένα πεδία.',required:'Το πεδίο είναι υποχρεωτικό.',invalidUsername:'Χρησιμοποιήστε 3–100 λατινικούς χαρακτήρες, αριθμούς, τελεία, παύλα ή κάτω παύλα.',passwordShort:'Ο κωδικός πρέπει να έχει τουλάχιστον 10 χαρακτήρες.',requestFailed:'Η ενέργεια απέτυχε. Δοκιμάστε ξανά.',
  evaluatingStudent:'Φοιτητής προς αξιολόγηση',gradeCategories:'Κατηγορίες βαθμολόγησης',showQrCode:'Προβολή QR Code',qrCodeSession:'QR Code Συνεδρίας',copyLink:'Αντιγραφή συνδέσμου',linkCopied:'Ο σύνδεσμος αντιγράφηκε!',scanToGrade:'Σαρώστε το QR Code για αξιολόγηση',inputMode:'Τρόπος βαθμολόγησης',numbersMode:'Πλήκτρα 1-5',dropdownMode:'Μενού επιλογής (Dropdown)',selectGrade:'Επιλέξτε βαθμό…',extendVoting:'+30 δευτ.',timeRemainingFull:'Χρόνος που απομένει',timeUp:'Ο χρόνος έληξε',scorePoor:'1 - Ανεπαρκής',scoreFair:'2 - Μέτριος',scoreGood:'3 - Καλός',scoreVeryGood:'4 - Πολύ καλός',scoreExcellent:'5 - Άριστος',gradesCompleted:'κατηγορίες βαθμολογήθηκαν',
  evaluated:'Αξιολογημένη',noVotes:'Χωρίς ψήφους',
  importCsv:'Εισαγωγή CSV',csvImportTitle:'Μαζική εισαγωγή δεδομένων (CSV)',csvModeHierarchy:'Πλήρης δομή (Μάθημα, Περίοδος, Ομάδα, Φοιτητές)',csvModeStudents:'Εισαγωγή φοιτητών σε ομάδα',csvPasteOrUpload:'Επικόλληση κειμένου CSV ή επιλογή αρχείου',csvFile:'Αρχείο CSV',csvSampleDownload:'Πρότυπο CSV',csvPreview:'Προεπισκόπηση εγγραφών',csvImportBtn:'Εκτέλεση εισαγωγής',csvSuccessSummary:'Η εισαγωγή ολοκληρώθηκε επιτυχώς!',csvRowsCount:'εγγραφές έτοιμες για εισαγωγή',csvNoValidRows:'Δεν βρέθηκαν έγκυρες γραμμές στο CSV.',csvTargetGroup:'Ομάδα προορισμού',csvPastePlaceholder:'Επικολλήστε εδώ γραμμές CSV (π.χ. Μάθημα, Περίοδος, Ομάδα, Φοιτητής, Θέμα)...',csvSampleHierarchy:'Λήψη προτύπου δομής',csvSampleStudents:'Λήψη προτύπου φοιτητών',
  reopenVoting:'Άνοιγμα κλειστής (60δ)',reopenShort:'Άνοιγμα (60δ)',reopenVotingHint:'Άνοιγμα κλειστής ψηφοφορίας για καθυστερημένες απαντήσεις (προεπιλογή 60 δευτερόλεπτα)',delayedResponses:'Καθυστερημένες απαντήσεις',
  categories:'Κατηγορίες',category:'Κατηγορία',categoryName:'Όνομα κατηγορίας',addCategory:'Προσθήκη κατηγορίας',removeCategory:'Αφαίρεση',defaultCategories:'3 Προεπιλεγμένες κατηγορίες',resetDefaultCategories:'Επαναφορά στις 3 προεπιλογές',manageCategories:'Κατηγορίες ψηφοφορίας',categoriesForPresentation:'Κατηγορίες ψηφοφορίας παρουσίασης',categoriesCount:'κατηγορίες',equalWeights:'Ισοκατανομή βαρύτητας',weightPercent:'Βαρύτητα (%)',totalWeight:'Σύνολο βαρύτητας',applyToAllPresentations:'Εφαρμογή σε όλες τις παρουσιάσεις της συνεδρίας',appliedToAll:'Εφαρμόστηκε σε όλες τις παρουσιάσεις',categorySaved:'Οι κατηγορίες αποθηκεύτηκαν.',atLeastOneCategory:'Απαιτείται τουλάχιστον μία κατηγορία αξιολόγησης.',categoriesHint:'3 κατηγορίες είναι η προεπιλογή. Μπορείτε να προσθέσετε περισσότερες κατηγορίες ή να αφαιρέσετε κατά τη δημιουργία της συνεδρίας.',presetOriginality:'Πρωτοτυπία & Καινοτομία',presetVisuals:'Διαφάνειες & Εποπτικά μέσα',presetTiming:'Τήρηση χρόνου & Ροή',presetQnA:'Απαντήσεις σε ερωτήσεις & Q&A',studentVoteDemo:'Demo φοιτητή (Ψηφοφορία)',studentVoteDemoHint:'Δείτε ακριβώς τι βλέπουν οι φοιτητές στο κινητό τους κατά την ψηφοφορία',studentViewPreview:'Προεπισκόπηση οθόνης φοιτητή',
  resetPassword:'Επαναφορά κωδικού',resetPasswordTitle:'Επαναφορά κωδικού χρήστη',resetPasswordPrompt:'Ορίστε νέο προσωρινό κωδικό ή αφήστε κενό για αυτόματη δημιουργία. Ο χρήστης θα υποχρεωθεί να τον αλλάξει στην επόμενη σύνδεσή του.',resetPasswordSuccess:'Ο κωδικός επαναφέρθηκε επιτυχώς!',tempPasswordIs:'Προσωρινός κωδικός πρόσβασης:',mustChangeNextLogin:'Υποχρεωτική αλλαγή στην επόμενη σύνδεση',confirmDeleteUser:'Είστε σίγουροι ότι θέλετε να διαγράψετε οριστικά αυτόν τον χρήστη;',confirmDeactivateUser:'Είστε σίγουροι ότι θέλετε να απενεργοποιήσετε αυτόν τον χρήστη;',confirmReactivateUser:'Είστε σίγουροι ότι θέλετε να επανενεργοποιήσετε αυτόν τον χρήστη;',cannotDeleteSelf:'Δεν μπορείτε να διαγράψετε τον εαυτό σας.',cannotDeactivateSelf:'Δεν μπορείτε να απενεργοποιήσετε τον εαυτό σας.',copyPassword:'Αντιγραφή προσωρινού κωδικού',passwordCopied:'Αντιγράφηκε!',userDeactivated:'Ο χρήστης απενεργοποιήθηκε.',userReactivated:'Ο χρήστης επανενεργοποιήθηκε.',userDeleted:'Ο χρήστης διαγράφηκε επιτυχώς.',temporaryPasswordHint:'Σημειώστε τον προσωρινό κωδικό και δώστε τον χρήστη. Στην επόμενη σύνδεση θα του ζητηθεί υποχρεωτικά να ορίσει νέο κωδικό.',
  resetDatabase:'Εκκαθάριση βάσης δεδομένων',resetDatabasePrompt:'Προσοχή! Αυτή η ενέργεια θα διαγράψει οριστικά όλα τα δεδομένα (μαθήματα, ομάδες, φοιτητές, συνεδρίες, ψηφοφορίες) και θα επαναφέρει τη βάση στην αρχική της κατάσταση.',resetDatabaseSuccess:'Η βάση δεδομένων εκκαθαρίστηκε επιτυχώς.',confirmResetDb:'Είστε σίγουροι ότι θέλετε να εκκαθαρίσετε πλήρως τη βάση δεδομένων;'
} as const;

const en:Record<keyof typeof el,string>={
  hierarchy:'Course structure',
  students:'Students',student:'Student',presentationSubject:'Presentation subject',presentationDate:'Presentation date',manageStudents:'Manage students',theme:'Color palette',themeHint:'Choose a muted color for your account.',logo:'Logo',uploadLogo:'Upload logo',logoUploaded:'Logo uploaded.',timeRemaining:'Time remaining',seconds:'seconds',
  app:'Presentation Voting',login:'Sign in',username:'Username',password:'Password',fullName:'Full name',dashboard:'Dashboard',account:'Account',admin:'Administration',logout:'Sign out',language:'Ελληνικά',loading:'Loading…',
  lecturerDashboard:'Lecturer dashboard',courses:'Courses',course:'Course',courseName:'Course name',description:'Description',periods:'Academic periods',period:'Period',periodName:'Period name',groups:'Groups',group:'Group',groupTitle:'Group title',sessions:'Sessions',session:'Session',sessionTitle:'Session title',sessionDate:'Date',add:'Add',create:'Create',cancel:'Cancel',save:'Save',noItems:'No entries yet.',select:'Select…',
  addCourse:'New course',addPeriod:'New period',addGroup:'New group',addSession:'New session',created:'The entry was created successfully.',courseFirst:'Create a course first.',periodFirst:'Create an academic period first.',groupFirst:'Create a group first.',
  users:'Users',lecturer:'Lecturer',addLecturer:'New lecturer',temporaryPassword:'Temporary password',passwordHint:'At least 10 characters. The user must change it at first sign-in.',usernameHint:'3–100 characters: Latin letters, numbers, dot, hyphen, or underscore.',active:'Active',inactive:'Inactive',userCreated:'The lecturer was created and must change the temporary password at first sign-in.',
  branding:'Institutional identity',universityName:'University',schoolName:'School',departmentName:'Department',background:'Background',none:'None',solid:'Solid color',gradient:'Gradient',backgroundValue:'Background value',saved:'Changes saved.',
  participationLink:'Participation link',presentations:'Presentations',withoutTitle:'Untitled',votes:'votes',edit:'Edit',open:'Open',skip:'Skip',restore:'Restore',close:'Close',activate:'Activate',complete:'Complete',confirmComplete:'Permanently complete this session?',reveal:'Reveal results',projector:'Projector',presenterDetails:'Presenter details',title:'Title',results:'Results',noEvaluated:'There are no evaluated presentations.',rank:'Rank',presenter:'Presenter',score:'Score',
  live:'LIVE',presentation:'Presentation',submitRating:'Submit rating',voteSaved:'Your vote was saved. You may change it while voting remains open.',sessionCompleted:'The session is complete',waitingNext:'Waiting for the next presentation',waitingForNextPresentation:'Waiting for the next voting to open...',presentationQueue:'Presentation Queue',autoUpdate:'This screen will update automatically.',votingOpen:'VOTING OPEN',waitingPresentation:'Waiting for a presentation',
  mandatoryPassword:'Password change required',changePassword:'Change password',temporaryReplace:'You must replace the temporary password before continuing.',currentPassword:'Current password',newPassword:'New password',confirmPassword:'Confirm new password',passwordMismatch:'The new passwords do not match.',passwordChanged:'Password changed successfully.',
  removeManagement:'Safe management',deactivate:'Deactivate',reactivate:'Reactivate',delete:'Delete',archiveAction:'Archive',confirmDeactivate:'Deactivate user',confirmReactivate:'Reactivate user',confirmDelete:'Permanently delete',confirmArchive:'Archive',actionDone:'Action completed.',  criterionScience:'Scientific documentation',criterionClarity:'Clarity and organization',criterionThinking:'Critical thinking',draft:'Draft',activeStatus:'Active',completed:'Completed',archived:'Archived',pending:'Pending',votingOpenStatus:'Voting open',closed:'Closed',skipped:'Skipped',validation:'Check the highlighted fields.',required:'This field is required.',invalidUsername:'Use 3–100 Latin letters, numbers, dots, hyphens, or underscores.',passwordShort:'The password must contain at least 10 characters.',requestFailed:'The action failed. Please try again.',
  evaluatingStudent:'Student being graded',gradeCategories:'Grading categories',showQrCode:'Show QR Code',qrCodeSession:'Session QR Code',copyLink:'Copy link',linkCopied:'Link copied!',scanToGrade:'Scan QR Code to grade',inputMode:'Grading input',numbersMode:'1-5 Buttons',dropdownMode:'Dropdown menu',selectGrade:'Select score…',extendVoting:'+30 sec',timeRemainingFull:'Time remaining',timeUp:'Time is up',scorePoor:'1 - Unsatisfactory',scoreFair:'2 - Fair',scoreGood:'3 - Good',scoreVeryGood:'4 - Very good',scoreExcellent:'5 - Excellent',gradesCompleted:'categories graded',
  evaluated:'Evaluated',noVotes:'No votes',
  importCsv:'Import CSV',csvImportTitle:'Batch Data Import (CSV)',csvModeHierarchy:'Full Structure (Course, Period, Group, Students)',csvModeStudents:'Import students into group',csvPasteOrUpload:'Paste CSV text or choose file',csvFile:'CSV File',csvSampleDownload:'CSV Template',csvPreview:'Records preview',csvImportBtn:'Run import',csvSuccessSummary:'Import completed successfully!',csvRowsCount:'records ready to import',csvNoValidRows:'No valid rows found in CSV.',csvTargetGroup:'Target group',csvPastePlaceholder:'Paste CSV rows here (e.g. Course, Period, Group, Student, Topic)...',csvSampleHierarchy:'Download structure template',csvSampleStudents:'Download students template',
  reopenVoting:'Reopen voting (60s)',reopenShort:'Reopen (60s)',reopenVotingHint:'Reopen closed voting for delayed responses (default 60 seconds)',delayedResponses:'Delayed responses',
  categories:'Categories',category:'Category',categoryName:'Category name',addCategory:'Add category',removeCategory:'Remove',defaultCategories:'3 Default categories',resetDefaultCategories:'Reset to 3 default categories',manageCategories:'Voting categories',categoriesForPresentation:'Presentation voting categories',categoriesCount:'categories',equalWeights:'Equal weight distribution',weightPercent:'Weight (%)',totalWeight:'Total weight',applyToAllPresentations:'Apply to all presentations in this session',appliedToAll:'Applied to all presentations',categorySaved:'Categories saved.',atLeastOneCategory:'At least one grading category is required.',categoriesHint:'3 categories are the default. You can add more categories or remove them when creating the session.',presetOriginality:'Originality & Innovation',presetVisuals:'Slides & Visual aids',presetTiming:'Timekeeping & Flow',presetQnA:'Q&A & Answering questions',studentVoteDemo:'Student Voting Demo',studentVoteDemoHint:'See what students see on their phones while voting',studentViewPreview:'Student Screen Preview',
  resetPassword:'Reset password',resetPasswordTitle:'Reset user password',resetPasswordPrompt:'Set a new temporary password or leave blank to generate automatically. The user will be required to change it on their next login.',resetPasswordSuccess:'Password reset successfully!',tempPasswordIs:'Temporary password:',mustChangeNextLogin:'Must change on next login',confirmDeleteUser:'Are you sure you want to permanently delete this user?',confirmDeactivateUser:'Are you sure you want to deactivate this user?',confirmReactivateUser:'Are you sure you want to reactivate this user?',cannotDeleteSelf:'You cannot delete yourself.',cannotDeactivateSelf:'You cannot deactivate yourself.',copyPassword:'Copy temporary password',passwordCopied:'Copied!',userDeactivated:'User was deactivated.',userReactivated:'User was reactivated.',userDeleted:'User was deleted successfully.',temporaryPasswordHint:'Note the temporary password and share it with the user. On their next login, they will be forced to choose a new password.',
  resetDatabase:'Reset database',resetDatabasePrompt:'Warning! This action will permanently delete all data (courses, groups, students, sessions, votes) and reset the database to its pristine initial state.',resetDatabaseSuccess:'Database reset successfully.',confirmResetDb:'Are you sure you want to completely reset the database?'
};

export type TranslationKey=keyof typeof el;
export const translations={el,en};

export function translateStatus(status: string, t: (k: TranslationKey) => string): string {
  switch (status?.toUpperCase()) {
    case 'DRAFT': return t('draft');
    case 'ACTIVE': return t('activeStatus');
    case 'COMPLETED': return t('completed');
    case 'ARCHIVED': return t('archived');
    case 'PENDING': return t('pending');
    case 'VOTING_OPEN': return t('votingOpenStatus');
    case 'EVALUATED': return t('evaluated');
    case 'NO_VOTES': return t('noVotes');
    case 'CLOSED': return t('closed');
    case 'SKIPPED': return t('skipped');
    default: return status;
  }
}

export const apiMessages:Record<Language,Record<string,string>>={
  el:{'Invalid credentials':'Λανθασμένα στοιχεία σύνδεσης','Not found':'Δεν βρέθηκε'},
  en:{'Λανθασμένα στοιχεία σύνδεσης':'Invalid username or password','Μη έγκυρος κωδικός':'Invalid current password','Ο νέος κωδικός πρέπει να είναι διαφορετικός':'The new password must be different','Το όνομα χρήστη υπάρχει ήδη':'That username already exists','Δεν βρέθηκε':'Not found','Μη έγκυρη επιλογή':'Invalid selection','Μη έγκυρα στοιχεία χρήστη ή κωδικός μικρότερος από 10 χαρακτήρες':'Invalid user details or password shorter than 10 characters','Ο κωδικός πρέπει να έχει τουλάχιστον 10 χαρακτήρες':'The password must contain at least 10 characters','Μη έγκυρο χρώμα':'Invalid color','Υποστηρίζονται μόνο έγκυρες εικόνες PNG, JPEG και WebP':'Only valid PNG, JPEG, and WebP images are supported','Μη έγκυρος εξυπηρετητής':'Invalid host','Το μάθημα χρησιμοποιείται από ομάδα ή συνεδρία':'The course is used by a group or session','Η περίοδος χρησιμοποιείται από ομάδα ή συνεδρία':'The period is used by a group or session','Η ομάδα χρησιμοποιείται από συνεδρία':'The group is used by a session','Μόνο πρόχειρες ή DEMO συνεδρίες διαγράφονται οριστικά':'Only draft or demo sessions can be permanently deleted','Πάρα πολλές προσπάθειες· δοκιμάστε αργότερα':'Too many attempts; try again later','Πάρα πολλές υποβολές· περιμένετε λίγο':'Too many submissions; wait a moment'}
};

export function translateError(error:unknown,language:Language){
  const fallback=translations[language].requestFailed;
  const message=error instanceof Error?error.message:String(error||fallback);
  const known=apiMessages[language][message];
  if(known)return known;
  if(message.includes('username:')&&message.includes('pattern'))return translations[language].invalidUsername;
  if(message.includes('password:')&&message.includes('10'))return translations[language].passwordShort;
  if(message.includes('full_name:'))return `${translations[language].fullName}: ${translations[language].required}`;
  return message||fallback;
}
